runs:
  using: "composite"
  steps:
    - name: Run AccuKnox IaC Scanner
      shell: bash
      env:
        ACCUKNOX_ENDPOINT: ${{ inputs.endpoint }}
        ACCUKNOX_LABEL: ${{ inputs.label }}
        ACCUKNOX_TOKEN: ${{ inputs.token }}
        DIRECTORY: ${{ inputs.directory }}
        FILE: ${{ inputs.file }}
        COMPACT: ${{ inputs.compact }}
        QUIET: ${{ inputs.quiet }}
        SOFT_FAIL: ${{ inputs.soft_fail }}
        FRAMEWORK: ${{ inputs.framework }}
      run: |
        set -e
        echo "Downloading AccuKnox ASPM Scanner..."
        curl -L https://github.com/accuknox/aspm-scanner-cli/releases/download/v0.13.4/accuknox-aspm-scanner -o accuknox-aspm-scanner
        chmod +x accuknox-aspm-scanner

        CMD_ARGS=""
        [ -n "$FILE" ] && CMD_ARGS="$CMD_ARGS --file $FILE"
        [ -n "$DIRECTORY" ] && CMD_ARGS="$CMD_ARGS --directory $DIRECTORY"
        [ "$COMPACT" = "true" ] && CMD_ARGS="$CMD_ARGS --compact"
        [ "$QUIET" = "true" ] && CMD_ARGS="$CMD_ARGS --quiet"
        [ -n "$FRAMEWORK" ] && CMD_ARGS="$CMD_ARGS --framework $FRAMEWORK"

        SOFT_FAIL_ARG=""
        [ "$SOFT_FAIL" = "true" ] && SOFT_FAIL_ARG="--soft-fail-on iac"

        echo "Running AccuKnox IaC scan..."
        ./accuknox-aspm-scanner scan iac $CMD_ARGS $SOFT_FAIL_ARG \
          --container-mode \
          --repo-url "$GITHUB_SERVER_URL/$GITHUB_REPOSITORY.git" \
          --repo-branch "${GITHUB_REF#refs/heads/}"
