name: "AccuKnox IaC Scanner"
description: "Run AccuKnox Infrastructure as Code (IaC) scan on the repository"
author: "Vickydew1"
branding:
  icon: "shield"
  color: "purple"

inputs:
  file:
    description: 'Specify a file for scanning; cannot be used with directory input. Filter runners by file type, e.g., ".tf" for Terraform.'
    required: false
    default: ""
  directory:
    description: 'Directory with infrastructure code and/or package manager files to scan'
    required: false
    default: "."
  compact:
    description: "Do not display code blocks in output"
    required: false
    default: true
  quiet:
    description: "Display only failed checks"
    required: false
    default: true
  soft_fail:
    description: "Do not return an error code if there are failed checks"
    required: false
    default: true
  framework:
    description: "Run only on a specific infrastructure, Supported: Kubernetes & Terraform"
    required: false
    default: ""
  endpoint:
    description: "The URL of the CSPM panel to push the scan results to"
    required: false
    default: "cspm.demo.accuknox.com"
  label:
    description: "The label created in AccuKnox SaaS for associating scan results."
    required: true
  token:
    description: "The token for authenticating with the CSPM panel"
    required: true

runs:
  using: composite
  steps:
    - name: Run AccuKnox IaC Scanner
      shell: bash
      env:
        ACCUKNOX_ENDPOINT: ${{ inputs.endpoint }}
        ACCUKNOX_TOKEN: ${{ inputs.token }}
        ACCUKNOX_LABEL: ${{ inputs.label }}
        FILE: ${{ inputs.file }}
        DIRECTORY: ${{ inputs.directory }}
        COMPACT: ${{ inputs.compact }}
        QUIET: ${{ inputs.quiet }}
        SOFT_FAIL: ${{ inputs.soft_fail }}
        FRAMEWORK: ${{ inputs.framework }}
      run: |
        echo "Downloading AccuKnox ASPM Scanner..."
        curl -L https://github.com/accuknox/aspm-scanner-cli/releases/download/v0.13.4/accuknox-aspm-scanner -o accuknox-aspm-scanner
        chmod +x accuknox-aspm-scanner

        SOFT_FAIL_ARG=""
        [ "$SOFT_FAIL" = true ] && SOFT_FAIL_ARG="--softfail"

        CMD_ARGS=""
        [ -n "$FILE" ] && CMD_ARGS="$CMD_ARGS --file $FILE"
        [ -n "$DIRECTORY" ] && CMD_ARGS="$CMD_ARGS --directory $DIRECTORY"
        [ "$COMPACT" = true ] && CMD_ARGS="$CMD_ARGS --compact"
        [ "$QUIET" = true ] && CMD_ARGS="$CMD_ARGS --quiet"
        [ -n "$FRAMEWORK" ] && CMD_ARGS="$CMD_ARGS --framework $FRAMEWORK"

        REPO_URL="--repo-url ${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}.git"
        REPO_BRANCH="--repo-branch ${GITHUB_REF#refs/heads/}"

        echo "Running AccuKnox scan with label: $ACCUNOX_LABEL on endpoint: $ACCUNOX_ENDPOINT"
        ./accuknox-aspm-scanner scan $SOFT_FAIL_ARG iac $CMD_ARGS --container-mode $REPO_URL $REPO_BRANCH
      continue-on-error: true
