name: "AccuKnox Container Scanner"
description: "Run AccuKnox Container scan on a specified image and push results to AccuKnox Console"

inputs:
  endpoint:
    description: "URL of the AccuKnox Console to push scan results"
    required: true
    default: "cspm.demo.accuknox.com"
  token:
    description: "API token to authenticate with the AccuKnox Console"
    required: true
  image:
    description: "Name of the container image to scan"
    required: true
  tag:
    description: "Version tag for the container image"
    required: true
    default: ${{ github.run_id }}
  severity:
    description: "Severity levels to block pipeline (LOW, MEDIUM, HIGH, CRITICAL)"
    required: false
    default: ""
  label:
    description: "Label used in AccuKnox Console to tag scan results"
    required: true

runs:
  using: "composite"
  steps:
    - name: Run AccuKnox Container Scanner
      shell: bash
      env:
        ACCUKNOX_ENDPOINT: ${{ inputs.endpoint }}
        ACCUKNOX_TOKEN: ${{ inputs.token }}
        IMAGE: ${{ inputs.image }}
        TAG: ${{ inputs.tag }}
        SEVERITY: ${{ inputs.severity }}
        LABEL: ${{ inputs.label }}
      run: |
        if [ -z "$ACCUKNOX_ENDPOINT" ] || [ -z "$ACCUKNOX_TOKEN" ] || [ -z "$IMAGE" ] || [ -z "$TAG" ] || [ -z "$LABEL" ]; then
          echo "ERROR: endpoint, token, image, tag, and label must be set!"
          exit 1
        fi

        echo "Downloading AccuKnox ASPM Scanner..."
        curl -L https://github.com/accuknox/aspm-scanner-cli/releases/download/v0.13.4/accuknox-aspm-scanner -o accuknox-aspm-scanner
        chmod +x accuknox-aspm-scanner

        CMD_ARGS="--image $IMAGE:$TAG --label $LABEL"
        [ -n "$SEVERITY" ] && CMD_ARGS="$CMD_ARGS --severity $SEVERITY"

        echo ./accuknox-aspm-scanner scan container --command "$CMD_ARGS" --container-mode
        ./accuknox-aspm-scanner scan container --command "$CMD_ARGS" --container-mode
