name: "AccuKnox IaC"
description: "Run AccuKnox Infrastructure as Code (IaC) scan on the repository"

branding:
  icon: "shield"
  color: "purple"

inputs:
  directory:
    description: 'Directory with infrastructure code to scan'
    required: false
    default: "."
  file:
    description: 'Specify a file for scanning; cannot be used with directory input.'
    required: false
    default: ""
  soft_fail:
    description: "Do not return an error code if there are failed checks"
    required: false
    default: false
  framework:
    description: "Run only on a specific infrastructure, Kubernetes or Terraform"
    required: false
    default: ""
  accuknox_endpoint:
    description: "CSPM panel endpoint URL"
    required: true
  accuknox_label:
    description: "Label in AccuKnox SaaS for scan results"
    required: true
  accuknox_token:
    description: "Token for authenticating with CSPM panel"
    required: true

runs:
  using: "composite"
  steps:
    - name: Run AccuKnox IaC Scanner
      shell: bash
      env:
        ACCUKNOX_ENDPOINT: ${{ inputs.accuknox_endpoint }}
        ACCUKNOX_LABEL: ${{ inputs.accuknox_label }}
        ACCUKNOX_TOKEN: ${{ inputs.accuknox_token }}
        DIRECTORY: ${{ inputs.directory }}
        FILE: ${{ inputs.file }}
        SOFT_FAIL: ${{ inputs.soft_fail }}
        FRAMEWORK: ${{ inputs.framework }}
      run: |
        if [ -z "$ACCUKNOX_ENDPOINT" ] || [ -z "$ACCUKNOX_LABEL" ] || [ -z "$ACCUKNOX_TOKEN" ]; then
          echo "ERROR: ACCUKNOX_ENDPOINT, ACCUKNOX_LABEL, and ACCUKNOX_TOKEN must be set!"
          exit 1
        fi

        echo "Downloading AccuKnox ASPM Scanner..."
        curl -L https://github.com/accuknox/aspm-scanner-cli/releases/download/v0.14.0/accuknox-aspm-scanner -o accuknox-aspm-scanner
        chmod +x accuknox-aspm-scanner

        CMD_ARGS=""
        [ -n "$FILE" ] && CMD_ARGS="$CMD_ARGS --file $FILE"
        [ -n "$DIRECTORY" ] && CMD_ARGS="$CMD_ARGS --directory $DIRECTORY"
        [ -n "$FRAMEWORK" ] && CMD_ARGS="$CMD_ARGS --framework $FRAMEWORK"

        if [ "$SOFT_FAIL" = "true" ]; then
          SOFT_FAIL_ARG="--softfail"
        fi

        echo "Running AccuKnox IaC scan..."
        ./accuknox-aspm-scanner scan $SOFT_FAIL_ARG iac --command "$CMD_ARGS" --container-mode --repo-url "$GITHUB_SERVER_URL/$GITHUB_REPOSITORY.git" --repo-branch "${GITHUB_REF#refs/heads/}" --keep-results || true

    - name: Upload IaC Scan Results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: iac-scan-results
        path: results.json
        retention-days: 30
